# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.7.3

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/PlateMapper

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            if [[ ! -d /home/circleci/anaconda3 ]]; then
                wget https://repo.continuum.io/miniconda/Anaconda3-latest-Linux-x86_64.sh -O anaconda.sh &&
                bash anaconda.sh -b -f -p /home/circleci/anaconda2;
            else
                echo "Using cached miniconda";
            fi
            source ~/anaconda3/bin/activate PlateMapper
            conda config --set always_yes yes
            conda update -q conda
            conda config --add channels conda-forge
            conda install -n root conda-build
            pip install --no-deps codacy-coverage

      - save_cache:
          paths:
            - ./anaconda3
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run tests!
      # this example uses Django's built-in test-runner
      # other common Python testing frameworks include pytest and nose
      # https://pytest.org
      # https://nose.readthedocs.io
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python manage.py test

      - store_artifacts:
          path: test-reports
          destination: test-reports